### ISSUE TITLE
Add instruction to initial text entry area that disappears after first edit.

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#1]
This must be customizable by visualization app.

**Comment by JMCanning78** [comment]
The visualization app would supply the initial text to be displayed in the text entry area.  It should probably be displayed with some different font highlighting like blue color and italics.  Perhaps the whole text can be auto-selected so that once the user types something, it erases the whole thing and resets the font to normal.

**Comment by lilypolonetsky** [comment]
issue1-instruction-text-entry
