### ISSUE TITLE
Convert global constants to class constants in VisualizationApp.py

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#11]
The top level (global) constants defined in VisualizationApp.py need to be constants within the VisualizationApp class to avoid potential name collisions.  Some examples are:
```
FONT_SIZE = 20
VALUE_FONT = ('Helvetica', FONT_SIZE)
VALUE_COLOR = 'black'
VARIABLE_FONT = ('Courier', FONT_SIZE * 8 // 10)
VARIABLE_COLOR = 'brown3'
```
Making this change requires updating the Array.py and SimpleSorting.py modules, too, which reference those constants.  Those modules also define their own constants that should be moved into the Array and SimpleArraySort classes.

**Comment by NataniaBirnbaum** [comment]
I realized I made a mistake after I linked the first pull request, so I had to go back and fix it and link a new pull request. There may still be some stuff that needs fixing, but the main issue is solved.
