### ISSUE TITLE
Code box horizontal scrollbar 

### ISSUE THREAD

**Issue by ShaniLewis** [JMCanning78/datastructures-visualization#114]
The code box horizontal scrollbar is a bug that applies to all the visualizations.   
When code that is too long for the code box is entered, the scroll bar can be used to view the entire line of code. However, if the window is expanded, the code box does not expand allowing a user to view the entire line of code without assistance from the scrollbar. Please enable the code box to expand when the window is expanded

**Comment by JMCanning78** [comment]
This is a problem in VisualizationApp.  One or more of the Tk frame widgets that hold the controls on the bottom of the screen is not configured right to expand with the window.  I haven't had a chance to look at it, but I'm pretty sure that's the problem.

**Comment by JMCanning78** [comment]
Created Issue114-fix-code-box-scrollbar branch for this work.
