### ISSUE TITLE
Add animation to DeleteRightmost operation

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#12]
The Array.py and SimpleSorting.py modules have a Delete Rightmost array cell operation.  This should be animated to use the `moveItemsOffCanvas` method of `visualizationApp`.  That will make it consistent with deleting an item from the array, and with inserting (which animates the arrival of the value from off of the canvas).

**Comment by shirapahmer** [comment]
Miriam and I created two branches that each resolve one of these issues, and created a pull request to have it merged with master.

**Comment by JMCanning78** [comment]
The animation was added to Delete Rightmost in SimpleSorting.py but I don't see it in Array.py.  I think #37 is still open for that purpose.
