### ISSUE TITLE
Add code display and highlighting in Array.py

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#13]
The Array.py module should show the code for each operation and highlight the snippet being executed, like SimpleSorting.py does.

**Comment by lilypolonetsky** [comment]
branch: issue13-array-code

**Comment by lilypolonetsky** [comment]
Finished find method code highlighting

**Comment by JMCanning78** [comment]
Working on this issue exposed the limitation of the current code display and highlighting: it only handles a single call level.  I wrote a design document on how to enhance the current mechanism to handle a stack of calls (https://github.com/JMCanning78/datastructures-visualization/blob/JMCanning78-call-stack-design/PythonVisualizations/design/CallStackVisualization.md).  Once some (all?) of that is implemented, we can apply it here.
