### ISSUE TITLE
Add Shellsort to AdvancedSorting visualization

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#143]
The Shellsort is another sorting algorithm like Quicksort that should be an operation in the AdvancedSorting.py visualization.  The sorting interval should be shown as part of the animation.  I don't think that simply moving the `inner` pointer by the interval `h` communicates the concept well.  The intervals could be visualized with a "comb" like drawing that points at all the cells for the current interval, `h`, or perhaps by thickening or enlarging the frames of those cells.  I kind of like the latter approach, although it sounds more complex.  The values of `h` and `nShifts` should be displayed as local variables.  

This issue depends on the completion of  PR #126.

The textbook code for the `Shellsort()` method (of the `SortArray.Array` class) is shown below.  The return of the `nShifts` as a result does not need to be shown as an output.
```
class Array(SortArray.Array):  # Base new Array class on SortArray
   
   def ShellSort(self):        # Sort using Shell's method:
      h = 1                    # Choose h to sort every h items
      while h * 3 < len(self): # Use Knuth's h sequence, find largest
         h = 3 * h + 1         # h that is less than array length
      nShifts = 0              # Count number of shifts
      while h > 0:             # Loop over decreasing h values
         for outer in range(h, len(self)): # Mark one item
            temp = self.get(outer)       # Store marked item in temp
            inner = outer                # Inner loop starts at mark
            while inner >= h and temp < self.get(inner-h): # If marked
               self.set(inner, self.get(inner-h)) # item smaller, then
               inner -= h                # shift item to right
               nShifts += 1              # Count shift 
            if inner < outer:  # If inner loop advanced a step, then
               self.set(inner, temp)     # Move marked item to 'hole'
               nShifts += 1    # and count the shift
         h = (h - 1) // 3      # Reduce h to sort smaller intervals
      return nShifts           # Return number of shifts
```

**Comment by lilypolonetsky** [comment]
created branch issue143-shellsort
