### ISSUE TITLE
Convert newQueue.py to use drawable class

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#16]
Change the newQueue.py visualization to use the drawable record class instead of `recordclass`.  The different versions of `recordclass` that come with Python have different ways of getting the list of fields in the record.  It's better that the visualization repo is "self-contained" and only depends on Python, tkinter, and standard Python libraries.

**Comment by adinabruce** [comment]
#45

**Comment by adinabruce** [comment]
finished converting newqueue to use drawable

**Comment by JMCanning78** [comment]
This should have been closed by the conclusion of PR #45, but wasn't linked at the time of the closure.
