### ISSUE TITLE
Add traverse operation to Array.py

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#19]
Show traversal by animating the copying of values in the array, to a list of numbers along the bottom of the canvas.  The code for the traverse() method in Chapter 2 is:
```
   def traverse(self, function=print):
      for j in range(self.__nItems): 
         function(self.__a[j])
```
Iterators haven't been introduced yet, so the animation should mimic the idea of printing out the values in the array.  The animation should show the `j` variable being incremented over the array, and the numeric values sliding into position in the "printed" output along the bottom.   The printed output should not include the colored squares used to indicate array cell contents since the values have been taken out of the array.  The spacing of the output values should be less than when they are in the array, to help indicate that they have been taken out and "processed".  When each value is animated, we could either animate the movement of its colored square and then make it disappear after the movement ends, or just animate the movement of the value.
The `j` index variable and the printed values should be added to the cleanup list so they will be removed in the next animation.

**Comment by lilypolonetsky** [comment]
branch is issue19-traverse-array
