### ISSUE TITLE
Use encoding='utf-8' to support different Windows system encoding

### ISSUE THREAD

**Issue by moonlit-melody** [JMCanning78/datastructures-visualization#312]
![image](https://github.com/JMCanning78/datastructures-visualization/assets/113663127/7d659695-58ac-40f7-bf43-b3abef4bef11)
I modified this [PythonVisualization->allVisualizationsCommon.py L88](https://github.com/JMCanning78/datastructures-visualization/blob/5a8500cd2a29bd97e00267004ee7f9e9021b7e5d/PythonVisualizations/allVisualizationsCommon.py#L88)
`with open(filename, 'r', encoding='utf-8') as f:`
It works flawless now. 
Thank you for providing those code examples!

**Comment by JMCanning78** [comment]
Fixed with commit 17aa9e4. Thanks for pointing this out, @moonlit-melody!
