### ISSUE TITLE
Slow animation speed can make the application seem frozen

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#42]
@lilypolonetsky 's https://github.com/JMCanning78/datastructures-visualization/pull/22#issuecomment-646145216 pointed out some potential bugs.   The second one might trip up some visualizations.

* When the speed slider is put all the way to the left, the sleep time passed as an argument to the `speed()` function is multiplied by 50 (at the far right, it is multiplied by 1).  If you pass a sleepTime of 0.2 or more, the interface is going to sleep 10+ seconds.    10 seconds is an enormously long time in interactive software.   Many users would assume the program froze.

We should cap the maximum time the `speed()` function  returns to be 10 seconds.  This cap would prevent any combination of user adjustment and program requested delay from lasting longer than 10 seconds.

**Comment by JMCanning78** [comment]
The `speed()` method is defined in VisualizationApp.py

**Comment by JMCanning78** [comment]
@Lara-Amar and @adinabruce, how is going on this Issue?

**Comment by ahelman** [comment]
How about a linear formula such as this one:
(sleepTime * ((self.SPEED_SCALE_MAX+self.SPEED_SCALE_MIN-self.speedScale.get())/self.SPEED_SCALE_DEFAULT))
slow = sleepTime * 2 (rounded up)
avg = sleepTime * 1
fast = sleepTime * 0.04 (rounded up)

Really the denominator can be replaced with any value, but the scale_default provides easy numbers to work with. Avg should = 1 I feel like. 

v.s. 

The current formula in use has x^(-1), which creates this skewed scale: (sleepTime * 50 * self.SPEED_SCALE_MIN / self.speedScale.get())
 slow = sleepTime * 50
avg = (about) sleepTime * 2 (rounded up) 
fast = sleepTime * 1

**Comment by JMCanning78** [comment]
That's an interesting proposal.  It keeps the ratio of the fastest to the slowest at 50 and makes the scale linear.  I think, however, since human perception is more sensitive to ratios, it's better to use the 1/x scale.   For vision and hearing, the threshold to distinguish one stimulus to another is in the form of a ratio.  For example to see that something is brighter or larger, or to hear that one note is louder than another, the threshold is based on the ratio of the brightness/size/volume.  That may not carry over directly to perception of speed, but my sense is that the 1/x scale gives more reasonable "slow" "medium" and "fast" playback speed of the animations we've done.
Aside from the discussion of linear vs. 1/x scale, the primary consideration is whether the user interface becomes unresponsive.  Since Python and Tkinter are single-threaded, sleeping makes the interface temporarily unresponsive.  The idea of this Issue is to cap that unresponsive period, independently from what sleepTime and the `speed()` scaling do.

**Comment by ahelman** [comment]
Oh ok. 

Capping it at 10 secs is a little long though, no?

**Comment by JMCanning78** [comment]
Yes, 10 seconds will be an "eternity" to someone used to modern computers and knowing what to expect from the operation being visualized.  To someone just seeing the data structure for the first time and struggling to understand it, they will want to go slow.  They can slow it indefinitely by pressing Pause, so maybe we don't need to allow wait's of 10 seconds.  I'm wondering if there are people with disabilities that might benefit from a pace that slow where they could play the animation super slow without hitting Pause/Play repeatedly.  That is probably a very small audience, so maybe 5 seconds or 3 seconds would be a better cap.

**Comment by JMCanning78** [comment]
This was completed in commit c9e49f42 in master
