### ISSUE TITLE
Fix code box in SimpleSorting.py 

### ISSUE THREAD

**Issue by shirasassoon** [JMCanning78/datastructures-visualization#61]
When a user clicks on a simple sort button and the animation occurs, the box that displays the simple sort method code on the bottom right of the screen cuts off the beginning of the first line. The first line should be displayed completely.

**Comment by shirasassoon** [comment]
Created a branch called Issue61-code-box-simplesort

**Comment by JMCanning78** [comment]
I think this happens for all the methods where the longest line is wider than what will fit in the `codeText` window.
The `.see()` calls are supposed to show the text at a particular index,  but a call to `.see("1.0")` when the code is added to the window didn't immediately fix that when I looked at it.  It might have something to do with the horizontal scrollbar.

**Comment by michalkaufman** [comment]
Shira Sassoon and I created a new branch called Issue61-horizontal-scrollbar-simplesort that has the new updates. We noticed that the files on our initial branch did not work properly.

**Comment by JMCanning78** [comment]
Here's a suggestion on what might work.  Try adding an explicit scroll to the left edge after the text is added to the `codeText` widget, e.g.,

`self.codeText.xview(MOVETO, 0)`

**Comment by JMCanning78** [comment]
So the idea about using `self.codeText.xview(MOVETO, 0)` didn't work out.   Try this instead: add a call to self.window.update() after the first call to `.see()` in the `showCode()` method.   Here's the snippet:

```
        # Add code at top of text widget (above stack boundary, if any)
        self.codeText.insert('1.0', code + '\n')
        self.codeText.see('1.0')
        self.window.update()
```

When I try that on my Mac, it starts off the codeText box with the scrolling all the way to the left and leaves it there.  See if that works on Windows as well and try to find conditions where it doesn't work.
