### ISSUE TITLE
Create a PriorityQueue visualization based on VisualizationApp

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#73]
Create a PriorityQueue class based on VisualizationApp.  There is no
visualization yet built for this data structure but it shares similarities
with OrderedArray.py and Queue.py.

The PriorityQueue should accept short text or numeric values, maybe 8
characters max.  Numeric values can be stored internally as strings and
compared as strings.  

Implement the animated methods for:
 * New Queue (empty with a given max capacity)
 * Insert (at rear)
 * Remove (from front)
 * Peek (at front)

Peek should copy the first element of the queue to the bottom of the
canvas, like the Traverse operation in Array.py.  The value should be
labeled "Front". 

Clicking on an item in the queue should update the argument for the
Insert operation to be that item's value.

**Comment by NataniaBirnbaum** [comment]
In a priority queue, the "deque" mode is a bit of a misnomer. Should I change queue/deque to be min/max, like a heap?

**Comment by JMCanning78** [comment]
@NataniaBirnbaum, thanks for being precise with the terminology.  I think some of the confusion here is that the earlier visualizations for queues and heaps were developed before the students saw the code that would be in the textbook.

I've never heard of using the deque API with a priority queue, so I'm not sure where you saw that reference.  The SimpleQueue.py program has some deque capabilities in it, but we are taking those out (see Issue #28).  In priority queues, inserts always go to the position determined by the item's priority, so insert front and insert back are the same operation.  Priority queues usually only allow removal of the highest priority item and not the lowest (which would would be at the front and back of a deque, respectively).

As to your question about making the PriorityQueue support minimum and maximum  values as being the highest priority, I want to keep it simple and implement only the version in the textbook code.   That version treats the minimum key value as the highest priority and sorts the items in increasing order of their keys (the item at index 0 has the minimum key).

**Comment by JMCanning78** [comment]
Here's a copy of the textbook code for the PriorityQueue:

```
# Implement a Priority Queue data structure using a Python list

def identity(x):  return x            # Identity function

class PriorityQueue(object):
   def __init__(self, size, pri=identity): # Constructor
      self.__maxSize = size           # Size of array
      self.__que = [None] * size      # Queue stored as a list
      self.__pri = pri                # Func. to get item priority
      self.__nItems = 0               # no items in queue
    
   def insert(self, item):            # Insert item at rear of
      if self.isFull():               # priority queue if not full
         raise Exception("Queue overflow")
      j = self.__nItems - 1           # Start at front
      while j >= 0 and (              # Look for place by priority
            self.__pri(item) >= self.__pri(self.__que[j])):
         self.__que[j+1] = self.__que[j] # Shift items to front
         j -= 1                       # Step towards rear
      self.__que[j+1] = item          # Insert new item at rear
      self.__nItems += 1
      return True
    
   def remove(self):                  # Return front item of priority
      if self.isEmpty():              # queue, if not empty, & remove
         raise Exception("Queue underflow")
      self.__nItems -= 1              # One fewer item in queue
      front = self.__que[self.__nItems] # Store front most
      self.__que[self.__nItems] = None # Remove item reference        
      return front
    
   def peek(self):                    # Return frontmost item
      return None if self.isEmpty() else self.__que[self.__nItems-1]
        
   def isEmpty(self): return self.__nItems == 0
    
   def isFull(self):  return self.__nItems == self.__maxSize
```
