### ISSUE TITLE
Add status and error messages to SkipList.py

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#83]
The SkipList visualization doesn't provide any textual user feedback for its operations.  Please add:

- Result of search operation: either item found or item not found (see Array.py)
- Result of delete operation: either item deleted or item not found (see Array.py)
- Failure of insert operation: either because key is a duplicate or because there isn't enough room to add a new link
- Limitation on fill operation: explain that number of items filled was limited to those that would fit in the window.

Change the names of the operations to capitalized words and their order for consistency with the other visualizations: Search, Insert, Delete, and Fill.

**Comment by shirasassoon** [comment]
created a branch called Issue83-statuserror-messages-skiplist.py
