### ISSUE TITLE
Create Advanced Sorting VisualizationApp

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#95]
Create the Advanced Sorting VisualizationApp by renaming Sorting.py into AdvancedSorting.py.  Create a new file, SortingBase.py that implements a subclass of VisualizationApp with the common sorting operations that are shared by
SimpleSorting.py and the new AdvancedSorting.py.   The class hierarchy that will eventually be built looks like:

```
                            VisualizationApp
                                   |
                              SortingBase
                            /      |     \
              ------------         |       ------------
            /                      |                    \
SimpleArraySort            AdvancedArraySort         MergeSort
```

Separate issues address converting `SimpleArraySort` (in SimpleSorting.py) and  a separate visualization for mergesort  to subclass `SortingBase`.  **This issue only covers the creation of SortingBase.py and AdvancedSorting.py.**

Advanced Sorting should have the following operations:

 * New   -> Create a new, empty array of size N where N can be up to a third of the canvas width
 * Random Fill  -> Fill all array cells with values randomly selected between 0-99 (duplicates allowed)
 * Insert  -> Insert a new user-specified value between 0-99 at the right end (highest index) of the array, if it is not full
 * Delete  -> Delete a the first user-specified value found in the array (using linear search)
 * Remove from End -> Delete the last item of the array
 * Quicksort -> Sort the array using the quicksort algorithm
 * Shuffle -> Randomly shuffle the array contents

Show all cell values as colored rectangles filling part of a rectangle like this: ![Array cells filled by key size](https://user-images.githubusercontent.com/26984827/87611029-d8ff1080-c6bb-11ea-92b9-b1f03c4421ca.png)
A value of 0 fills half the rectangle and  a value of 99 fills all of it.  Show the cell values with text inside the rectangle when the width of the cell is above some threshold (let's try 20 pixels).  When the user asks for arrays with more cells and the width gets below that threshold, show only the colored rectangle.  When users click on a rectangle, fill the argument 0 text entry field with the numeric value.  That allows them to click a cell, and the delete that cell (if it doesn't have a duplicate earlier in the array).

Note, this change in array cell appearance will also change `SimpleArraySort` once it subclasses `SortingBase`.

Leave the code for mergesort in the AdvancedSorting.py file for now.  It will be moved to another visualization in a separate issue.  Shellsort will be added to AdvancedSorting.py in a separate issue.

**Comment by shirasassoon** [comment]
Created a branch called Issue95-advancedsorting-visualizationapp

**Comment by JMCanning78** [comment]
I put you back on as the assignee, Lily, since you committed changes to PR #126 yesterday.
