### ISSUE TITLE
Add code and highlighting for operations in Stack.py

### ISSUE THREAD

**Issue by JMCanning78** [JMCanning78/datastructures-visualization#97]
Display the code for each of the operations in the Stack visualization and highlight the active code.  All of the operations are O(1) so there is very little highlighting needed.  Make a call to `wait(0.2)` for each change in highlight so users will have some time to see it.  Display the code for the New, Push, Pop, and Peek operations, including the call to `isEmpty()` in Peek.  Add an animation for the assignment of the `top` item in `pop()` to a temporary variable, before it is moved off the canvas.

Here's the textbook code.

```
class Stack(object):
   def __init__(self, max):            # Constructor
      self.__stackList = [None] * max  # The stack stored as a list
      self.__top = -1                  # No items initially
        
   def push(self, item):               # Insert item at top of stack
      self.__top += 1                  # Advance the pointer
      self.__stackList[self.__top] = item  # Store item
        
   def pop(self):                      # Remove top item from stack
      top = self.__stackList[self.__top]   # Top item 
      self.__stackList[self.__top] = None  # Remove item reference
      self.__top -= 1                  # Decrease the pointer
      return top                       # Return top item
    
   def peek(self):                     # Return top item
      if not self.isEmpty():           # If stack is not empty
         return self.__stackList[self.__top] # Return the top item
    
   def isEmpty(self):                  # Check if stack is empty
      return self.__top < 0

   def isFull(self):                   # Check if stack is full
      return self.__top >= len(self.__stackList) - 1
```

Note the code _**does not have error checking**_ for popping from an empty stack or pushing onto a full one.  That's because this is one of the first data structures covered in the textbook and the focus is initially on understanding the data operations.  The visualization code, must do those error checks; they just won't appear in the code.  There's a discussion in the textbook about when and why error checks should be included in the data structure implementation.  Later data structures include error checking in the code.

**Comment by lilypolonetsky** [comment]
branch issue97-code-highlight-stack
